export type ScotchStyle = "Single Malt" | "Blended" | "Blended Malt" | "Single Grain" | "Cask Strength" | "Peated" | "Sherry Cask" | "Bourbon Cask";
export type WineType = ScotchStyle;
export interface TopWineSeed { producer: string; name: string; wineType: ScotchStyle; region?: string; country?: string; }
const SM: ScotchStyle = "Single Malt"; const B: ScotchStyle = "Blended"; const BM: ScotchStyle = "Blended Malt"; const SG: ScotchStyle = "Single Grain"; const CS: ScotchStyle = "Cask Strength"; const P: ScotchStyle = "Peated"; const SC: ScotchStyle = "Sherry Cask"; const BC: ScotchStyle = "Bourbon Cask";
interface ProducerRow { producer: string; country?: string; wines: { name: string; type: ScotchStyle; region?: string }[]; }
const CATALOG: ProducerRow[] = [
  {producer:"Glenfiddich",country:"Scotland",wines:[{name:"Glenfiddich 12 Year",type:SM,region:"Speyside"},{name:"Glenfiddich 15 Year Solera",type:SM,region:"Speyside"},{name:"Glenfiddich 18 Year",type:SM,region:"Speyside"},{name:"Glenfiddich 21 Year Gran Reserva",type:SC,region:"Speyside"},{name:"Glenfiddich IPA Experiment",type:SM,region:"Speyside"}]},
  {producer:"The Macallan",country:"Scotland",wines:[{name:"Macallan 12 Sherry Oak",type:SC,region:"Speyside"},{name:"Macallan 12 Double Cask",type:SM,region:"Speyside"},{name:"Macallan 15 Double Cask",type:SM,region:"Speyside"},{name:"Macallan 18 Sherry Oak",type:SC,region:"Speyside"},{name:"Macallan Rare Cask",type:SC,region:"Speyside"},{name:"Macallan Edition No. 6",type:SM,region:"Speyside"}]},
  {producer:"Laphroaig",country:"Scotland",wines:[{name:"Laphroaig 10 Year",type:P,region:"Islay"},{name:"Laphroaig Quarter Cask",type:P,region:"Islay"},{name:"Laphroaig 10 Cask Strength",type:CS,region:"Islay"},{name:"Laphroaig Lore",type:P,region:"Islay"},{name:"Laphroaig 25 Year",type:P,region:"Islay"}]},
  {producer:"Lagavulin",country:"Scotland",wines:[{name:"Lagavulin 16 Year",type:P,region:"Islay"},{name:"Lagavulin 8 Year",type:P,region:"Islay"},{name:"Lagavulin Distillers Edition",type:P,region:"Islay"},{name:"Lagavulin 12 Cask Strength",type:CS,region:"Islay"}]},
  {producer:"Ardbeg",country:"Scotland",wines:[{name:"Ardbeg 10 Year",type:P,region:"Islay"},{name:"Ardbeg Uigeadail",type:CS,region:"Islay"},{name:"Ardbeg Corryvreckan",type:CS,region:"Islay"},{name:"Ardbeg An Oa",type:P,region:"Islay"},{name:"Ardbeg Wee Beastie 5 Year",type:P,region:"Islay"}]},
  {producer:"Bruichladdich",country:"Scotland",wines:[{name:"Bruichladdich The Classic Laddie",type:SM,region:"Islay"},{name:"Bruichladdich Islay Barley",type:SM,region:"Islay"},{name:"Port Charlotte 10 Year",type:P,region:"Islay"},{name:"Octomore (various)",type:CS,region:"Islay"}]},
  {producer:"Bowmore",country:"Scotland",wines:[{name:"Bowmore 12 Year",type:P,region:"Islay"},{name:"Bowmore 15 Year",type:SC,region:"Islay"},{name:"Bowmore 18 Year",type:P,region:"Islay"}]},
  {producer:"Caol Ila",country:"Scotland",wines:[{name:"Caol Ila 12 Year",type:P,region:"Islay"},{name:"Caol Ila 18 Year",type:P,region:"Islay"},{name:"Caol Ila Distillers Edition",type:P,region:"Islay"}]},
  {producer:"Bunnahabhain",country:"Scotland",wines:[{name:"Bunnahabhain 12 Year",type:SM,region:"Islay"},{name:"Bunnahabhain 18 Year",type:SC,region:"Islay"},{name:"Bunnahabhain Toiteach A Dha",type:P,region:"Islay"}]},
  {producer:"Kilchoman",country:"Scotland",wines:[{name:"Kilchoman Machir Bay",type:P,region:"Islay"},{name:"Kilchoman Sanaig",type:P,region:"Islay"},{name:"Kilchoman 100% Islay",type:P,region:"Islay"}]},
  {producer:"Highland Park",country:"Scotland",wines:[{name:"Highland Park 12 Year",type:SM,region:"Islands"},{name:"Highland Park 18 Year",type:SM,region:"Islands"},{name:"Highland Park Cask Strength",type:CS,region:"Islands"}]},
  {producer:"Talisker",country:"Scotland",wines:[{name:"Talisker 10 Year",type:SM,region:"Islands"},{name:"Talisker 18 Year",type:SM,region:"Islands"},{name:"Talisker Storm",type:SM,region:"Islands"},{name:"Talisker Distillers Edition",type:SM,region:"Islands"}]},
  {producer:"The Glenlivet",country:"Scotland",wines:[{name:"Glenlivet 12 Year",type:SM,region:"Speyside"},{name:"Glenlivet 14 Year Cognac Cask",type:SM,region:"Speyside"},{name:"Glenlivet 15 Year French Oak",type:SM,region:"Speyside"},{name:"Glenlivet 18 Year",type:SM,region:"Speyside"},{name:"Glenlivet Nadurra Oloroso",type:CS,region:"Speyside"}]},
  {producer:"The Balvenie",country:"Scotland",wines:[{name:"Balvenie DoubleWood 12",type:SM,region:"Speyside"},{name:"Balvenie Caribbean Cask 14",type:SM,region:"Speyside"},{name:"Balvenie PortWood 21",type:SM,region:"Speyside"},{name:"Balvenie Single Barrel 15 Sherry",type:SC,region:"Speyside"}]},
  {producer:"Glenmorangie",country:"Scotland",wines:[{name:"Glenmorangie Original 10",type:BC,region:"Highland"},{name:"Glenmorangie Lasanta (Sherry)",type:SC,region:"Highland"},{name:"Glenmorangie Quinta Ruban (Port)",type:SM,region:"Highland"},{name:"Glenmorangie Nectar d Or (Sauternes)",type:SM,region:"Highland"},{name:"Glenmorangie 18 Year",type:SM,region:"Highland"},{name:"Glenmorangie Signet",type:SM,region:"Highland"}]},
  {producer:"Aberlour",country:"Scotland",wines:[{name:"Aberlour 12 Double Cask",type:SC,region:"Speyside"},{name:"Aberlour 16 Double Cask",type:SC,region:"Speyside"},{name:"Aberlour A Bunadh (Cask Strength)",type:CS,region:"Speyside"}]},
  {producer:"GlenDronach",country:"Scotland",wines:[{name:"GlenDronach 12 Original",type:SC,region:"Highland"},{name:"GlenDronach 15 Revival",type:SC,region:"Highland"},{name:"GlenDronach 18 Allardice",type:SC,region:"Highland"},{name:"GlenDronach 21 Parliament",type:SC,region:"Highland"}]},
  {producer:"Springbank",country:"Scotland",wines:[{name:"Springbank 10 Year",type:SM,region:"Campbeltown"},{name:"Springbank 15 Year",type:SM,region:"Campbeltown"},{name:"Longrow Peated",type:P,region:"Campbeltown"},{name:"Hazelburn 10 Year",type:SM,region:"Campbeltown"}]},
  {producer:"Glen Scotia",country:"Scotland",wines:[{name:"Glen Scotia 15 Year",type:SM,region:"Campbeltown"},{name:"Glen Scotia Victoriana",type:CS,region:"Campbeltown"},{name:"Glen Scotia Double Cask",type:SM,region:"Campbeltown"}]},
  {producer:"Oban",country:"Scotland",wines:[{name:"Oban 14 Year",type:SM,region:"Highland"},{name:"Oban Distillers Edition",type:SM,region:"Highland"}]},
  {producer:"Dalmore",country:"Scotland",wines:[{name:"Dalmore 12 Year",type:SC,region:"Highland"},{name:"Dalmore 15 Year",type:SC,region:"Highland"},{name:"Dalmore 18 Year",type:SC,region:"Highland"},{name:"Dalmore Cigar Malt",type:SC,region:"Highland"},{name:"Dalmore King Alexander III",type:SM,region:"Highland"}]},
  {producer:"Dalwhinnie",country:"Scotland",wines:[{name:"Dalwhinnie 15 Year",type:SM,region:"Highland"},{name:"Dalwhinnie Distillers Edition",type:SM,region:"Highland"}]},
  {producer:"Cragganmore",country:"Scotland",wines:[{name:"Cragganmore 12 Year",type:SM,region:"Speyside"},{name:"Cragganmore Distillers Edition",type:SM,region:"Speyside"}]},
  {producer:"Clynelish",country:"Scotland",wines:[{name:"Clynelish 14 Year",type:SM,region:"Highland"},{name:"Clynelish Distillers Edition",type:SM,region:"Highland"}]},
  {producer:"Glenkinchie",country:"Scotland",wines:[{name:"Glenkinchie 12 Year",type:SM,region:"Lowland"},{name:"Glenkinchie Distillers Edition",type:SM,region:"Lowland"}]},
  {producer:"Auchentoshan",country:"Scotland",wines:[{name:"Auchentoshan 12 Year",type:SM,region:"Lowland"},{name:"Auchentoshan Three Wood",type:SM,region:"Lowland"},{name:"Auchentoshan American Oak",type:BC,region:"Lowland"}]},
  {producer:"Bladnoch",country:"Scotland",wines:[{name:"Bladnoch 10 Year",type:SM,region:"Lowland"},{name:"Bladnoch Vinaya",type:SM,region:"Lowland"}]},
  {producer:"Arran",country:"Scotland",wines:[{name:"Arran 10 Year",type:SM,region:"Islands"},{name:"Arran 18 Year",type:SM,region:"Islands"},{name:"Arran Sherry Cask",type:SC,region:"Islands"},{name:"Arran Quarter Cask",type:SM,region:"Islands"}]},
  {producer:"Jura",country:"Scotland",wines:[{name:"Jura 10 Year",type:SM,region:"Islands"},{name:"Jura 18 Year",type:SM,region:"Islands"},{name:"Jura Superstition",type:P,region:"Islands"}]},
  {producer:"Tobermory",country:"Scotland",wines:[{name:"Tobermory 12 Year",type:SM,region:"Islands"},{name:"Ledaig 10 Year (Peated)",type:P,region:"Islands"}]},
  {producer:"Edradour",country:"Scotland",wines:[{name:"Edradour 10 Year",type:SM,region:"Highland"},{name:"Edradour 12 Caledonia",type:SC,region:"Highland"}]},
  {producer:"Ben Nevis",country:"Scotland",wines:[{name:"Ben Nevis 10 Year",type:SM,region:"Highland"}]},
  {producer:"Royal Lochnagar",country:"Scotland",wines:[{name:"Royal Lochnagar 12 Year",type:SM,region:"Highland"}]},
  {producer:"Tomatin",country:"Scotland",wines:[{name:"Tomatin 12 Year",type:SM,region:"Highland"},{name:"Tomatin 14 Port Cask",type:SM,region:"Highland"},{name:"Tomatin Legacy",type:SM,region:"Highland"}]},
  {producer:"Deanston",country:"Scotland",wines:[{name:"Deanston 12 Year",type:SM,region:"Highland"},{name:"Deanston 18 Year",type:SM,region:"Highland"},{name:"Deanston Virgin Oak",type:SM,region:"Highland"}]},
  {producer:"GlenAllachie",country:"Scotland",wines:[{name:"GlenAllachie 10 Year",type:SM,region:"Speyside"},{name:"GlenAllachie 12 Year",type:SM,region:"Speyside"},{name:"GlenAllachie 15 Year",type:SC,region:"Speyside"},{name:"GlenAllachie 10 Cask Strength",type:CS,region:"Speyside"}]},
  {producer:"Benriach",country:"Scotland",wines:[{name:"BenRiach The Original Ten",type:SM,region:"Speyside"},{name:"BenRiach The Smoky Ten",type:P,region:"Speyside"},{name:"BenRiach 12 Sherry Wood",type:SC,region:"Speyside"}]},
  {producer:"Glenfarclas",country:"Scotland",wines:[{name:"Glenfarclas 12 Year",type:SC,region:"Speyside"},{name:"Glenfarclas 15 Year",type:SC,region:"Speyside"},{name:"Glenfarclas 21 Year",type:SC,region:"Speyside"},{name:"Glenfarclas 105 Cask Strength",type:CS,region:"Speyside"}]},
  {producer:"Craigellachie",country:"Scotland",wines:[{name:"Craigellachie 13 Year",type:SM,region:"Speyside"},{name:"Craigellachie 17 Year",type:SM,region:"Speyside"}]},
  {producer:"Mortlach",country:"Scotland",wines:[{name:"Mortlach 12 Year",type:SM,region:"Speyside"},{name:"Mortlach 16 Year",type:SM,region:"Speyside"},{name:"Mortlach 20 Year",type:SM,region:"Speyside"}]},
  {producer:"Johnnie Walker",country:"Scotland",wines:[{name:"Johnnie Walker Black Label",type:B,region:"Scotland"},{name:"Johnnie Walker Green Label 15",type:BM,region:"Scotland"},{name:"Johnnie Walker Gold Label Reserve",type:B,region:"Scotland"},{name:"Johnnie Walker Blue Label",type:B,region:"Scotland"},{name:"Johnnie Walker 18 Year",type:B,region:"Scotland"}]},
  {producer:"Monkey Shoulder",country:"Scotland",wines:[{name:"Monkey Shoulder",type:BM,region:"Speyside"}]},
  {producer:"Compass Box",country:"Scotland",wines:[{name:"Compass Box Great King Street",type:B,region:"Scotland"},{name:"Compass Box Spice Tree",type:BM,region:"Scotland"},{name:"Compass Box Peat Monster",type:BM,region:"Scotland"},{name:"Compass Box Hedonism",type:SG,region:"Scotland"},{name:"Compass Box The Story of the Spaniard",type:BM,region:"Scotland"}]},
  {producer:"Chivas Regal",country:"Scotland",wines:[{name:"Chivas Regal 12 Year",type:B,region:"Scotland"},{name:"Chivas Regal 18 Year",type:B,region:"Scotland"}]},
  {producer:"Dewars",country:"Scotland",wines:[{name:"Dewars 12 Year",type:B,region:"Scotland"},{name:"Dewars 15 Year",type:B,region:"Scotland"},{name:"Dewars 18 Year",type:B,region:"Scotland"}]},
  {producer:"Famous Grouse",country:"Scotland",wines:[{name:"Famous Grouse",type:B,region:"Scotland"},{name:"Famous Grouse Smoky Black",type:B,region:"Scotland"}]},
  {producer:"Naked Malt (Famous Grouse)",country:"Scotland",wines:[{name:"Naked Malt",type:BM,region:"Scotland"}]},
];
export const topWines: TopWineSeed[] = CATALOG.flatMap((row) => row.wines.map((w) => ({ producer: row.producer, name: w.name, wineType: w.type, region: w.region, country: row.country })));
export const TOP_COUNT = topWines.length;

// === Additional producers (expanded manifest) ===
const CATALOG2:ProducerRow[]=[
{producer:"Bruichladdich",country:"UK",wines:[{name:"Bruichladdich The Classic Laddie",type:SM,region:"Islay"},{name:"Bruichladdich Islay Barley",type:SM,region:"Islay"},{name:"Bruichladdich Port Charlotte 10",type:P,region:"Islay"},{name:"Bruichladdich Black Art",type:SM,region:"Islay"},{name:"Bruichladdich Octomore",type:P,region:"Islay"}]},
{producer:"Bunnahabhain",country:"UK",wines:[{name:"Bunnahabhain 12 Year",type:SM,region:"Islay"},{name:"Bunnahabhain 18 Year",type:SM,region:"Islay"},{name:"Bunnahabhain Stiùireadair",type:SM,region:"Islay"},{name:"Bunnahabhain Toiteach",type:P,region:"Islay"}]},
{producer:"Caol Ila",country:"UK",wines:[{name:"Caol Ila 12 Year",type:SM,region:"Islay"},{name:"Caol Ila 18 Year",type:SM,region:"Islay"},{name:"Caol Ila Distillers Edition",type:SM,region:"Islay"}]},
{producer:"Dalmore",country:"UK",wines:[{name:"Dalmore 12 Year",type:SM,region:"Highland"},{name:"Dalmore 15 Year",type:SM,region:"Highland"},{name:"Dalmore 18 Year",type:SM,region:"Highland"},{name:"Dalmore King Alexander III",type:SM,region:"Highland"},{name:"Dalmore Cigar Malt",type:SM,region:"Highland"}]},
{producer:"Craigellachie",country:"UK",wines:[{name:"Craigellachie 13 Year",type:SM,region:"Speyside"},{name:"Craigellachie 17 Year",type:SM,region:"Speyside"},{name:"Craigellachie 23 Year",type:SM,region:"Speyside"}]},
{producer:"Edradour",country:"UK",wines:[{name:"Edradour 10 Year",type:SM,region:"Highland"},{name:"Edradour Caledonia 12 Year",type:SM,region:"Highland"},{name:"Edradour Ballechin 10",type:P,region:"Highland"}]},
{producer:"Glen Scotia",country:"UK",wines:[{name:"Glen Scotia Double Cask",type:SM,region:"Campbeltown"},{name:"Glen Scotia 15 Year",type:SM,region:"Campbeltown"},{name:"Glen Scotia Victoriana",type:CS,region:"Campbeltown"},{name:"Glen Scotia 25 Year",type:SM,region:"Campbeltown"}]},
{producer:"Glenallachie",country:"UK",wines:[{name:"GlenAllachie 10 Year",type:SM,region:"Speyside"},{name:"GlenAllachie 12 Year",type:SM,region:"Speyside"},{name:"GlenAllachie 15 Year",type:SM,region:"Speyside"},{name:"GlenAllachie 10 Year Cask Strength",type:CS,region:"Speyside"}]},
{producer:"Tomatin",country:"UK",wines:[{name:"Tomatin 12 Year",type:SM,region:"Highland"},{name:"Tomatin 14 Year Port Finish",type:SM,region:"Highland"},{name:"Tomatin 18 Year",type:SM,region:"Highland"},{name:"Tomatin Legacy",type:SM,region:"Highland"}]},
{producer:"Deanston",country:"UK",wines:[{name:"Deanston 12 Year",type:SM,region:"Highland"},{name:"Deanston 18 Year",type:SM,region:"Highland"},{name:"Deanston Virgin Oak",type:SM,region:"Highland"}]},
{producer:"Tobermory",country:"UK",wines:[{name:"Tobermory 12 Year",type:SM,region:"Islands"},{name:"Tobermory Ledaig 10 Year",type:P,region:"Islands"},{name:"Tobermory 20 Year",type:SM,region:"Islands"}]},
{producer:"Benromach",country:"UK",wines:[{name:"Benromach 10 Year",type:SM,region:"Speyside"},{name:"Benromach 15 Year",type:SM,region:"Speyside"},{name:"Benromach Peat Smoke",type:P,region:"Speyside"},{name:"Benromach Contrasts: Organic",type:SM,region:"Speyside"}]},
{producer:"Glengoyne",country:"UK",wines:[{name:"Glengoyne 10 Year",type:SM,region:"Highland"},{name:"Glengoyne 12 Year",type:SM,region:"Highland"},{name:"Glengoyne 18 Year",type:SM,region:"Highland"},{name:"Glengoyne 21 Year",type:SM,region:"Highland"},{name:"Glengoyne Cask Strength",type:CS,region:"Highland"}]},
{producer:"Glencadam",country:"UK",wines:[{name:"Glencadam 10 Year",type:SM,region:"Highland"},{name:"Glencadam 13 Year",type:SM,region:"Highland"},{name:"Glencadam 15 Year",type:SM,region:"Highland"}]},
{producer:"Kilchoman",country:"UK",wines:[{name:"Kilchoman Machir Bay",type:P,region:"Islay"},{name:"Kilchoman Sanaig",type:P,region:"Islay"},{name:"Kilchoman Loch Gorm",type:P,region:"Islay"},{name:"Kilchoman 100% Islay",type:P,region:"Islay"}]},
{producer:"Wolfburn",country:"UK",wines:[{name:"Wolfburn Northland",type:SM,region:"Highland"},{name:"Wolfburn Aurora",type:SM,region:"Highland"},{name:"Wolfburn Morven",type:P,region:"Highland"}]},
{producer:"Compass Box",country:"UK",wines:[{name:"Compass Box Great King Street",type:B,region:"Scotland"},{name:"Compass Box Spice Tree",type:BM,region:"Scotland"},{name:"Compass Box Peat Monster",type:BM,region:"Scotland"},{name:"Compass Box Hedonism",type:SG,region:"Scotland"}]},
];
const expanded=CATALOG2.flatMap(row=>row.wines.map(w=>({producer:row.producer,name:w.name,wineType:w.type,region:w.region,country:row.country})));
(topWines as TopWineSeed[]).push(...expanded);
